Update README.md for void closure specs
IntrepidPursuits/swift-style-guide pull request #28
Opened 2016-11-30 18:02 UTC by brightredchilli

2016-11-30 18:58 UTC, paulrolfe commented
👍

2016-11-30 19:27 UTC, alexpersian requested changes
Content looks good. Only a small visual style change requested.

2016-11-30 19:27 UTC, alexpersian commented on README.md
> +#####Not this:
Please add an addition `#` to the `Not this:` that you've added. (6 total `#` to match visually)

2016-12-01 14:38 UTC, brightredchilli commented on README.md
> +#####Not this:
nice catch, thanks

2016-12-01 14:39 UTC, alexpersian approved these changes

2016-12-01 14:39 UTC, alexpersian commented
🚢

2016-12-01 14:45 UTC, merged