How to define an operator for protocol conformance
IntrepidPursuits/swift-style-guide pull request #37
Opened 2017-09-15 19:46 UTC by Tom-Le

Recommend defining an operator for protocol conformance within the scope of the extension or type declaration that declared the conformance, instead of having it elsewhere.

2017-09-16 12:58 UTC, alexpersian requested changes

2017-09-16 12:58 UTC, alexpersian commented on README.md
> +###### Like this:
Drop one `#` here to fix the bolding

2017-09-16 12:59 UTC, alexpersian commented
Looks great. Good addition to the style guide.

2017-10-12 23:12 UTC, alexpersian approved these changes

2017-10-13 14:25 UTC, tzm41 approved these changes

2018-06-20 14:49 UTC, Tom-Le commented
Whoops I totally slept on this. Going to merge it in today unless there are objections 😁

2018-06-20 20:04 UTC, merged